### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by YurkaninRyan**
May need to run Bundler command now before jekyll serve.

Autoprefixer doesn't seem to be working yet.  Still working on that.

@skeswa @CodyJamesCasey

### CODE REVIEW

**Comment by skeswa** [comment]
I can't figure out how to update jekyll :-\

**Comment by YurkaninRyan** [comment]
~~~ 
gem update jekyll 
~~~ 

Maybe?  Is it throwing errors?

**Comment by CodyJamesCasey** [comment]
@YurkaninRyan what is the 'Bundler' command?

**Comment by YurkaninRyan** [comment]
It's basically
~~~
npm install
~~~
for ruby

**Pull request merged**
